# Generated by Django 5.1 on 2024-08-16 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Efectivo', 'CASH'), ('Tarjeta de crédito', 'CARD'), ('Transferencia', 'TRANSFER')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('Futbol 5', 'FIVE'), ('Futbol 6', 'SIX'), ('Futbol 7', 'SEVEN'), ('Futbol 9', 'NINE'), ('Futbol 11', 'ELEVEN')], max_length=100)),
                ('status', models.CharField(choices=[('Disponible', 'AVAILABLE'), ('En mantenimiento', 'MAINTENANCE')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('finish_date', models.DateField()),
                ('status', models.CharField(choices=[('En progreso', 'IN_PROGRESS'), ('Finalizado', 'FINISHED')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('user_type', models.CharField(choices=[('Admin', 'ADMIN'), ('User', 'USER')], max_length=100)),
                ('preferences', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('captain', models.CharField(max_length=50)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fulbitoApi.tournament')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fulbitoApi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_one', to='fulbitoApi.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team_two', to='fulbitoApi.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='fulbitoApi.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='fulbitoApi.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='fulbitoApi.user'),
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pendiente', 'PENDING'), ('Confirmada', 'CONFIRMED'), ('Cancelada', 'CANCELED')], max_length=100)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='fulbitoApi.payment')),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulbitoApi.pitch')),
                ('team_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_team_one', to='fulbitoApi.team')),
                ('team_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_team_two', to='fulbitoApi.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='fulbitoApi.user')),
            ],
        ),
        migrations.AddField(
            model_name='pitch',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='fulbitoApi.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fulbitoApi.user'),
        ),
    ]
