# Generated by Django 4.2.4 on 2024-08-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulbitoApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='pitch',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='team_one',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='team_two',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user_id',
        ),
        migrations.AddField(
            model_name='reserve',
            name='client',
            field=models.CharField(default='client', max_length=50),
        ),
        migrations.AddField(
            model_name='reserve',
            name='payment_method',
            field=models.CharField(choices=[('MercadoPago', 'MercadoPago'), ('Efectivo', 'EFECTIVO')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'PENDING'), ('Confirmada', 'CONFIRMED'), ('Cancelada', 'CANCELED')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
