# Generated by Django 5.1 on 2024-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulbitoApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='payment',
        ),
        migrations.AddField(
            model_name='reserve',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'PENDING'), ('Confirmada', 'CONFIRMED')], default='Pendiente', max_length=10),
        ),
    ]
