# Generated by Django 5.1 on 2024-08-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulbitoApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='team_one',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='team_two',
        ),
        migrations.AddField(
            model_name='reserve',
            name='client',
            field=models.CharField(default='client', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
