# Generated by Django 5.1 on 2024-08-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulbitoApi', '0002_remove_team_user_id_remove_reserve_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='fulbitoApi.payment'),
        ),
    ]
