# Generated by Django 4.2.4 on 2024-08-28 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulbitoApi', '0002_remove_payment_user_id_remove_pitch_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='fulbitoApi.payment'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='pitch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fulbitoApi.pitch'),
        ),
    ]
