# Generated by Django 5.1 on 2024-08-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulbitoApi', '0003_alter_reserve_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='status',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(related_name='tournaments', to='fulbitoApi.team'),
        ),
    ]
